import express from 'express';
import {auth} from '../middleware/auth.js';
import Chat from '../models/Chat.js';
import Progress from '../models/Progress.js';
import YogaPlan from '../models/YogaPlan.js';
import axios from 'axios';
const r=express.Router();r.use(auth);
r.get('/history',async(req,res)=>{try{const chat=await Chat.findOne({userId:req.user._id}).sort({updatedAt:-1});res.json({messages:chat?.messages||[]});}catch(e){res.status(500).json({message:'Unable to load chat history'});}});
r.post('/chat',async(req,res)=>{try{const message=String(req.body.message||'').trim();if(!message)return res.status(400).json({message:'Chat message cannot be empty'});if(message.length>4000)return res.status(400).json({message:'Message is too long'});let chat=await Chat.findOne({userId:req.user._id}).sort({updatedAt:-1});if(!chat)chat=await Chat.create({userId:req.user._id,messages:[]});const progress=await Progress.findOne({userId:req.user._id});const plan=await YogaPlan.findOne({userId:req.user._id,active:true});const history=chat.messages.slice(-12).map(m=>({role:m.role,content:m.content}));const currentPlan=plan?.weeklySchedule?.map(x=>({day:x.day,sessionName:x.sessionName,duration:x.duration,focus:x.focus,status:x.status}));const response=await axios.post(`${process.env.AI_SERVICE_URL||'http://127.0.0.1:8001'}/chat`,{message,user_context:{name:req.user.name,goal:req.user.goal,experience:req.user.experienceLevel,duration:req.user.preferredDuration,preferredTime:req.user.preferredTime,frequency:req.user.preferences?.daysPerWeek,focusAreas:req.user.preferences?.focusAreas||[],styles:req.user.preferences?.styles||[],streak:progress?.currentStreak||0,current_plan:currentPlan||[]},conversation_history:history},{timeout:30000});const answer=response.data.response||'I could not generate a response right now.';chat.messages.push({role:'user',content:message},{role:'assistant',content:answer,sources:response.data.sources||[]});await chat.save();res.json({response:answer,recommendations:response.data.recommendations||[],sources:response.data.sources||[]});}catch(e){console.error('AI chat error',e?.message);res.status(503).json({message:'Yoga Jenny is temporarily unavailable. Please try again shortly.'});}});export default r;
